YªçŠx-®éÜj×¢ëiºÚ+Š§j[h‘éÜ¢éí÷~wN‹Z–‹­¦ëeŠw¬Ô‰ÕÍ”±¥•¹Ðˆì()¥µÁ½ÉÐìÕÍ•™™•Ð°ÕÍ•5•µ¼°ÕÍ•I•˜°ÕÍ•MÑ…Ñ”ô™É½´€‰É•…Ðˆì)¥µÁ½ÉÐ1¥¹¬™É½´€‰¹•áÐ½±¥¹¬ˆì)¥µÁ½ÉÐì(€ÉÉ½Ý1•™Ð°(€±•ÉÑQÉ¥…¹±”°(€	•±±I¥¹œ°(€…±•¹‘…ÉA±ÕÌ°(€¡•¬°(€¡•­¥É±”È°(€±½¬Ì°(€áÑ•É¹…±1¥¹¬°(€¥±•Q•áÐ°(€5…¥°°(€I•™É•Í¡Ü°(€M¡¥•±‘¡•¬°(€MÁ…É­±•Ì°(€`°)ô™É½´€‰±Õ¥‘”µÉ•…Ðˆì)¥µÁ½ÉÐÑåÁ”ìUÍ•Èô™É½´€‰ÍÕÁ…‰…Í”½ÍÕÁ…‰…Í”µ©Ìˆì)¥µÁ½ÉÐìÍÕÁ…‰…Í”ô™É½´€ˆ¸¸¼¸¸¼¸¸½±¥ˆ½ÍÕÁ…‰…Í”ˆì)¥µÁ½ÉÐì(€…Ñ¥½¹QåÁ•1…‰•°°(€…ÁÁÉ½Ù•á•ÕÑ¥Ù•Ñ¥½¹%Ñ•´°(€…ÑÑ•¹Ñ¥½¹1…‰•°°(€‘¥Íµ¥ÍÍá•ÕÑ¥Ù•A…¬°(€•á•ÕÑ•ÁÁÉ½Ù•‘á•ÕÑ¥Ù•Ñ¥½¹%Ñ•´°(€•á•ÕÑ¥Ù••¹ÑU¹…Ù…¥±…‰±”°(€±½…‘á•ÕÑ¥Ù•Ñ¥½¹A…­Ì°(€µ…É­á•ÕÑ¥Ù•A…­I•…°(€Í¹½½é•á•ÕÑ¥Ù•A…¬°(€ÍÕ‰µ¥Ñá•ÕÑ¥Ù•••‘‰…¬°(€Íå¹á•ÕÑ¥Ù•%¹‰½à°(€ÑåÁ”á•ÕÑ¥Ù•Ñ¥½¹%Ñ•´°(€ÑåÁ”á•ÕÑ¥Ù•Ñ¥½¹A…¬°(€ÑåÁ”á•ÕÑ¥Ù•••‘‰…­QåÁ”°)ô™É½´€ˆ¸¸¼¸¸¼¸¸½±¥ˆ½ØÈµ•á•ÕÑ¥Ù”µ…•¹Ðˆì)¥µÁ½ÉÐÍÑå±•Ì™É½´€ˆ¸½…ÑÑ•¹Ñ¥½¸¹µ½‘Õ±”¹ÍÌˆì)¥µÁ½ÉÐ¥¹Ñ•±±¥•¹•MÑå±•Ì™É½´€ˆ¸½…ÑÑ•¹Ñ¥½¸µ¥¹Ñ•±±¥•¹”¹µ½‘Õ±”¹ÍÌˆì)¥µÁ½ÉÐ¹½Ñ¥•MÑå±•Ì™É½´€ˆ¸½…ÑÑ•¹Ñ¥½¸µ¹½Ñ¥”¹µ½‘Õ±”¹ÍÌˆì()ÑåÁ”Ñ¥½¹9½Ñ¥”€ôì(€Ñ½¹”è€‰•ÉÉ½Èˆð€‰ÍÕ•ÍÌˆì(€Ñ¥Ñ±”èÍÑÉ¥¹œì(€µ•ÍÍ…”èÍÑÉ¥¹œì(€¥Ñ•µ%üèÍÑÉ¥¹œì(€¡É•˜üèÍÑÉ¥¹œì(€¡É•™1…‰•°üèÍÑÉ¥¹œì)ôì()™Õ¹Ñ¥½¸™½Éµ…ÑÑ•‘…Ñ”¡Ù…±Õ”èÍÑÉ¥¹œð¹Õ±°¤ì(€¥˜€ …Ù…±Õ”¤É•ÑÕÉ¸€‰9¼™¥á•‘•…‘±¥¹”ˆì(€É•ÑÕÉ¸¹•Ü…Ñ”¡Ù…±Õ”¤¹Ñ½1½…±•MÑÉ¥¹œ ‰•¸µˆ°ìÝ••­‘…äè€‰Í¡½ÉÐˆ°‘…äè€‰¹Õµ•É¥Œˆ°µ½¹Ñ è€‰Í¡½ÉÐˆ°¡½ÕÈè€ˆÈµ‘¥¥Ðˆ°µ¥¹ÕÑ”è€ˆÈµ‘¥¥Ðˆô¤ì)ô()™Õ¹Ñ¥½¸ÁÉ•Á…É•‘Q•áÐ¡¥Ñ•´èá•ÕÑ¥Ù•Ñ¥½¹%Ñ•´¤ì(€½¹ÍÐÙ…±Õ”€ô¥Ñ•´¹½¹Ñ•¹Ð¹‰½‘ä€üü¥Ñ•´¹½¹Ñ•¹Ð¹µ…É­‘½Ý¸€ÿÍùÞÚ$z{-®éÜj×ce. This version can no longer be approved."}</span><div>{link && <Link href={link.href} target={link.external ? "_blank" : undefined} rel={link.external ? "noreferrer" : undefined}>{link.label} <ExternalLink size={15} /></Link>}{selectedIsActive && <button onClick={() => void approveAndExecute(item)} disabled={Boolean(busy) || item.executionStatus === "completed" || item.executionStatus === "executing" || item.executionStatus === "cancelled" || (!executesOnApproval(item) && item.approvalStatus === "approved")}><Check size={16} /> {actionButtonLabel(item, busy === item.id)}</button>}</div></div>
            </article>; })}
          </section>

          {selected.sourceUrl && <a className={styles.sourceLink} href={selected.sourceUrl} target="_blank" rel="noreferrer">Open source conversation <ExternalLink size={15} /></a>}

          <section className={styles.feedback}><strong>Was the judgement right?</strong><div><button onClick={() => void feedback(selected, "correct_useful")} disabled={Boolean(busy)}>Correct and useful</button><button onClick={() => void feedback(selected, "important_no_interrupt")} disabled={Boolean(busy)}>Important, but don&apos;t interrupt</button><button onClick={() => void feedback(selected, "wrong_interpretation")} disabled={Boolean(busy)}>Wrong interpretation</button><button onClick={() => void feedback(selected, "not_important")} disabled={Boolean(busy)}>Not important</button></div></section>
        </>}
      </section>
    </div>}
  </main>;
}
